/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const GamesPenguinThrowerLazyRouteImport = createFileRoute(
  '/games/penguin-thrower',
)()
const GamesHealthyEaterLazyRouteImport = createFileRoute(
  '/games/healthy-eater',
)()
const GamesArcadeShooterLazyRouteImport = createFileRoute(
  '/games/arcade-shooter',
)()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const GamesPenguinThrowerLazyRoute = GamesPenguinThrowerLazyRouteImport.update({
  id: '/games/penguin-thrower',
  path: '/games/penguin-thrower',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/games/penguin-thrower.lazy').then((d) => d.Route),
)
const GamesHealthyEaterLazyRoute = GamesHealthyEaterLazyRouteImport.update({
  id: '/games/healthy-eater',
  path: '/games/healthy-eater',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/games/healthy-eater.lazy').then((d) => d.Route),
)
const GamesArcadeShooterLazyRoute = GamesArcadeShooterLazyRouteImport.update({
  id: '/games/arcade-shooter',
  path: '/games/arcade-shooter',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/games/arcade-shooter.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/games/arcade-shooter': typeof GamesArcadeShooterLazyRoute
  '/games/healthy-eater': typeof GamesHealthyEaterLazyRoute
  '/games/penguin-thrower': typeof GamesPenguinThrowerLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/games/arcade-shooter': typeof GamesArcadeShooterLazyRoute
  '/games/healthy-eater': typeof GamesHealthyEaterLazyRoute
  '/games/penguin-thrower': typeof GamesPenguinThrowerLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/games/arcade-shooter': typeof GamesArcadeShooterLazyRoute
  '/games/healthy-eater': typeof GamesHealthyEaterLazyRoute
  '/games/penguin-thrower': typeof GamesPenguinThrowerLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/arcade-shooter'
    | '/games/healthy-eater'
    | '/games/penguin-thrower'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/arcade-shooter'
    | '/games/healthy-eater'
    | '/games/penguin-thrower'
  id:
    | '__root__'
    | '/'
    | '/games/arcade-shooter'
    | '/games/healthy-eater'
    | '/games/penguin-thrower'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  GamesArcadeShooterLazyRoute: typeof GamesArcadeShooterLazyRoute
  GamesHealthyEaterLazyRoute: typeof GamesHealthyEaterLazyRoute
  GamesPenguinThrowerLazyRoute: typeof GamesPenguinThrowerLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/penguin-thrower': {
      id: '/games/penguin-thrower'
      path: '/games/penguin-thrower'
      fullPath: '/games/penguin-thrower'
      preLoaderRoute: typeof GamesPenguinThrowerLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/healthy-eater': {
      id: '/games/healthy-eater'
      path: '/games/healthy-eater'
      fullPath: '/games/healthy-eater'
      preLoaderRoute: typeof GamesHealthyEaterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/arcade-shooter': {
      id: '/games/arcade-shooter'
      path: '/games/arcade-shooter'
      fullPath: '/games/arcade-shooter'
      preLoaderRoute: typeof GamesArcadeShooterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  GamesArcadeShooterLazyRoute: GamesArcadeShooterLazyRoute,
  GamesHealthyEaterLazyRoute: GamesHealthyEaterLazyRoute,
  GamesPenguinThrowerLazyRoute: GamesPenguinThrowerLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
