/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const GamesHealthyEaterLazyRouteImport = createFileRoute(
  '/games/healthy-eater',
)()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const GamesHealthyEaterLazyRoute = GamesHealthyEaterLazyRouteImport.update({
  id: '/games/healthy-eater',
  path: '/games/healthy-eater',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/games/healthy-eater.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/games/healthy-eater': typeof GamesHealthyEaterLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/games/healthy-eater': typeof GamesHealthyEaterLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/games/healthy-eater': typeof GamesHealthyEaterLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/healthy-eater'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/healthy-eater'
  id: '__root__' | '/' | '/games/healthy-eater'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  GamesHealthyEaterLazyRoute: typeof GamesHealthyEaterLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/healthy-eater': {
      id: '/games/healthy-eater'
      path: '/games/healthy-eater'
      fullPath: '/games/healthy-eater'
      preLoaderRoute: typeof GamesHealthyEaterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  GamesHealthyEaterLazyRoute: GamesHealthyEaterLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
